/*
 * This source file was generated by the Gradle 'init' task
 */
package uas;

import uas.views.DeviceView;

public class App {
    public static void main(String[] args) {
        DeviceView deviceView = new DeviceView();
        deviceView.render();
    }
}